### ISSUE TITLE
Download Manager (GUI): table entries arу scattered all over the page  

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#32]
_Preconditions:_
- there few Zipped items

_Steps to reproduce:_
1. Open Download Manager
2. Take a look at elements table

_Result:_ 
table entries arу scattered all over the page   (see screenshot)

_Expected result_:
table elements should be ordered in a table (like for example Data Entries at Data tab)

**Comment by Stref** [comment]
![765](https://cloud.githubusercontent.com/assets/13001938/8358424/beabad28-1b68-11e5-8626-28bd7b389fa0.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Fix

After some research and testing, the Download Manager format issues listed herein and some others are now corrected in my local application build.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For First Release 

If time  permits, replace scrolling <table> design with jQuery Datatable design.  Use of jQuery DataTable should address issues with column alignment. 

Otherwise - remove <table> scroll bar 

Other changes for first release:

Increase table height 
TIme series archive - show file name only - increase font size

**Comment by ghost** [comment]
BCC - 07-Jul-2015

Per review meeting findings, revised table layout to address column alignment.  Also, increased table height.  For file name column - increased font size, displayed file name only

**Comment by Stref** [comment]
Validated on build from 14.08.2015
Became much better, but still not perfect:there is blank area at the right side of the table entries (see screenshot attached)
![159](https://cloud.githubusercontent.com/assets/13001938/9278275/73ad5782-42b8-11e5-8dda-486acdcef902.png)

**Expected result:** remove blank area 

Reopened

**Comment by ghost** [comment]
BCC - 18-Aug-2015 - Reviewed and reproduced reported issue

Recommendation: Fix

Proposed Fix: For the Download Manager table - found a simpler implementation supporting a fixed header with a dynamic vertical scroll bar.  Happily, this implementation results in an improved table appearance as well, as shown below...

![image](https://cloud.githubusercontent.com/assets/7917808/9338025/982844fa-45b0-11e5-9017-7ce1e71dd127.png)

**Comment by ghost** [comment]
Fixed - per 18-Aug-2015 comments
